CREATE TABLE CMD(OPER_CODE VARCHAR2(30)
                , TICKER   VARCHAR2(10)
                , MODIFIED TIMESTAMP DEFAULT SYSTIMESTAMP)
/

ALTER TABLE CMD ADD CONSTRAINT OPER_CODE_FK
  FOREIGN KEY (OPER_CODE)
  REFERENCES OPERATION(CODE);
                
COMMENT ON TABLE CMD IS 'Command interface for client';